# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R1pkBsitV_s_AmuGO6l1StUIp3UYTIHC
"""

import streamlit as st
import numpy as np
import requests
from PIL import Image, ImageOps
import base64
import io

st.title("Guess the Drawing")

canvas_result = st.image(
    np.zeros((400, 400, 3), dtype=np.uint8),
    caption="Draw Here",
    use_column_width=True,
    channels="RGB"
)

if canvas_result.image_data is not None:
    st.image(canvas_result.image_data)
    img = Image.fromarray((canvas_result.image_data * 255).astype(np.uint8)).convert("RGB")

    buffered = io.BytesIO()
    img.save(buffered, format="PNG")
    img_str = base64.b64encode(buffered.getvalue()).decode("utf-8")

    if st.button("Submit Drawing"):
        response = requests.post("http://127.0.0.1:5000/predict", json={"image": f"data:image/png;base64,{img_str}"})
        if response.status_code == 200:
            guess = response.json().get('guess')
            st.write(f"The model guesses: {guess}")
        else:
            st.write("There was an error in the prediction process.")
